--SEMPRE COMENTAR 
CREATE DATABASE Gufi_DDL;

--DEFINA O BANCO DE DADOS QUE VOCÊ DESEJA USAR 
USE	Gufi_DDL;

CREATE TABLE TipoUsuario (
	IdTipoUsuario		INT PRIMARY KEY IDENTITY,
	TituloTipoUsuario	VARCHAR(150) NOT NULL UNIQUE 
	);

CREATE TABLE TipoEvento (
	IdTipoEvento		INT PRIMARY KEY IDENTITY,
	TituloTipoEvento	VARCHAR(200) NOT NULL UNIQUE 
	);

CREATE TABLE Instituicao (
	IdInstituicao	INT PRIMARY KEY IDENTITY,
	CNPJ			CHAR(14) NOT NULL UNIQUE, 
	NomeFantasia	VARCHAR(200) NOT NULL UNIQUE,
	Endereco		VARCHAR(200) NOT NULL UNIQUE,
	);

CREATE TABLE Usuario (
	IdUsuario		INT PRIMARY KEY IDENTITY,
	NomeUsuario		VARCHAR(200) NOT NULL,
	Email			VARCHAR(200) NOT NULL UNIQUE,
	Senha			VARCHAR(200) NOT NULL,
	Genero			VARCHAR(200) NOT NULL,
	DataNascimento	DATETIME2 NOT NULL,
	TipoUsuario		INT FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario)
	);

CREATE TABLE Evento (
	IdEvento		INT PRIMARY KEY IDENTITY,
	DataEvento		DATETIME2 NOT NULL,
	NomeEvento		VARCHAR(200) NOT NULL,
	Descricao		VARCHAR(255) NOT NULL,
	AcessoLivre		BIT DEFAULT(1) NOT NULL,
	IdInstitucao	INT FOREIGN KEY REFERENCES Instituicao(IdInstituicao),
	IdTipoEvento	INT FOREIGN KEY REFERENCES TipoEvento(IdTipoEvento)
	);
	
CREATE TABLE Presenca (
	IdPresenca	INT PRIMARY KEY IDENTITY,
	Situacao	VARCHAR(200),
	IdUsuario	INT FOREIGN KEY REFERENCES Usuario(IdUsuario),
	IdEvento	INT FOREIGN KEY REFERENCES Evento(IdEvento)
	);
